
TICKS_PER_SECOND = 50
DEFAULT_TRAFIC_LIGHT_DURATION = 10 #seconds
GRADUATIONS_PER_METER = 100
CAR_LENGTH = 2*GRADUATIONS_PER_METER
CAR_SPEED = 20000*GRADUATIONS_PER_METER/(3600*TICKS_PER_SECOND) #in graduations/tick